export const WorkspacesData = [
    {
        id: 1,
        name: 'Workspace for Contracts',
        type: 'Contract',
        users: 200,
        lastUpdate: 4,
        image: 'https://source.unsplash.com/800x600/?office,work',
        icon: 'Building',
    },
    {
        id: 2,
        name: 'Incognito Inc.',
        type: 'Corporate',
        users: 25,
        lastUpdate: 3,
        image: 'https://source.unsplash.com/800x600/?office',
        icon: 'Building',
    },
    {
        id: 3,
        name: 'Client norms',
        type: 'Norms',
        users: 25,
        lastUpdate: 3,
        image: 'https://source.unsplash.com/800x600/?office,people',
        icon: 'Building',
    },
    {
        id: 4,
        name: 'Working norms',
        type: 'Norms',
        users: 50,
        lastUpdate: 30,
        image: 'https://source.unsplash.com/800x600/?desk',
        icon: 'Building',
    },
    {
        id: 5,
        name: 'Client contract',
        type: 'Contract',
        users: 25,
        lastUpdate: 3,
        image: 'https://source.unsplash.com/800x600/?work',
        icon: 'Building',
    },
    {
        id: 6,
        name: 'Client contract',
        type: 'Contract',
        users: 25,
        lastUpdate: 3,
        image: 'https://source.unsplash.com/800x600/?office,working',
        icon: 'Building',
    },
    {
        id: 7,
        name: 'Client contract',
        type: 'Contract',
        users: 25,
        lastUpdate: 3,
        image: 'https://source.unsplash.com/800x600/?homeoffice',
        icon: 'Building',
    },
]